/*SELECT ALL CUSTOMERS ALONG WITH THEIR ORDERS BUT ONLY
FOR CUSTOMER WHO HAS PLACED THEIR ORDER*/
SELECT first_name,country,customers.id,score,order_date,sales
FROM CUSTOMERS INNER JOIN ORDERS ON ID=CUSTOMER_ID;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;